apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  # labels:
  #   commit: $GIT_COMMIT_HASH
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: scanner
        # commit: $GIT_COMMIT_HASH
    spec:
      containers:
        - name: scanner
          # image: $PRIVATE_REPO/$GCR_PROJECT/$IMAGE_REPO/$BRANCH:$GIT_COMMIT_HASH
          image: 'gcr.io/black-nucleus-236512/scanner/scanner:0.1.1'
          env:
            - name: SERVER_PORT
              value: '3000'
            - name: GOOGLE_BUCKET_NAME
              value: rocketchat-cc-uploads
            - name: FILE_DOWNLOAD_DIR
              value: /tmp
            - name: DEBUG
              value: 'true'
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 400m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 400Mi
      tolerations:
        - operator: Exists
          effect: NoSchedule
